cmake_minimum_required(VERSION 3.20)

get_filename_component(_prototype "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_contracts "${_prototype}/contracts")
set(_examples "${_prototype}/examples/secondary-development")

function(_fail message_text)
  message(FATAL_ERROR "secondary-development contract validation: ${message_text}")
endfunction()

function(_read_json out file_path)
  if(NOT EXISTS "${file_path}")
    _fail("missing JSON file: ${file_path}")
  endif()
  file(READ "${file_path}" _text)
  string(JSON _kind ERROR_VARIABLE _error TYPE "${_text}")
  if(NOT _error STREQUAL "NOTFOUND" OR NOT _kind STREQUAL "OBJECT")
    _fail("invalid JSON object ${file_path}: ${_error}")
  endif()
  set(${out} "${_text}" PARENT_SCOPE)
endfunction()

function(_json_equal json_text expected)
  string(JSON _actual ERROR_VARIABLE _error GET "${json_text}" ${ARGN})
  if(NOT _error STREQUAL "NOTFOUND")
    _fail("missing JSON member '${ARGN}': ${_error}")
  endif()
  if(NOT _actual STREQUAL "${expected}")
    _fail("JSON member '${ARGN}' is '${_actual}', expected '${expected}'")
  endif()
endfunction()

function(_json_has out json_text)
  string(JSON _ignored ERROR_VARIABLE _error TYPE "${json_text}" ${ARGN})
  if(_error STREQUAL "NOTFOUND")
    set(${out} TRUE PARENT_SCOPE)
  else()
    set(${out} FALSE PARENT_SCOPE)
  endif()
endfunction()

# Evaluate the Draft 2020-12 keywords used by the immutable schemas in
# prototype/contracts.  Values carry their JSON type separately so strings are
# never reparsed as JSON source.
function(_schema_validate_node out_valid out_error instance_value instance_type schema_json root_schema context)
  _json_has(_has_ref "${schema_json}" \$ref)
  if(_has_ref)
    string(JSON _ref GET "${schema_json}" \$ref)
    if(NOT _ref MATCHES "^#/")
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: only local JSON Pointer refs are supported" PARENT_SCOPE)
      return()
    endif()
    string(SUBSTRING "${_ref}" 2 -1 _pointer)
    string(REPLACE "/" ";" _ref_path "${_pointer}")
    string(JSON _ref_schema ERROR_VARIABLE _ref_error GET "${root_schema}" ${_ref_path})
    if(NOT _ref_error STREQUAL "NOTFOUND")
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: unresolved schema ref ${_ref}" PARENT_SCOPE)
      return()
    endif()
    _schema_validate_node(_valid _error "${instance_value}" "${instance_type}" "${_ref_schema}" "${root_schema}" "${context}")
    set(${out_valid} "${_valid}" PARENT_SCOPE)
    set(${out_error} "${_error}" PARENT_SCOPE)
    return()
  endif()

  _json_has(_has_type "${schema_json}" type)
  if(_has_type)
    string(JSON _expected_type GET "${schema_json}" type)
    string(TOUPPER "${_expected_type}" _expected_type)
    if(NOT instance_type STREQUAL _expected_type)
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: type ${instance_type}, expected ${_expected_type}" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_const "${schema_json}" const)
  if(_has_const)
    string(JSON _const_type TYPE "${schema_json}" const)
    string(JSON _const_value GET "${schema_json}" const)
    if(NOT instance_type STREQUAL _const_type OR NOT instance_value STREQUAL _const_value)
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: value does not equal schema const" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_enum "${schema_json}" enum)
  if(_has_enum)
    string(JSON _enum_length LENGTH "${schema_json}" enum)
    set(_enum_match FALSE)
    if(_enum_length GREATER 0)
      math(EXPR _enum_last "${_enum_length} - 1")
      foreach(_index RANGE 0 ${_enum_last})
        string(JSON _enum_type TYPE "${schema_json}" enum ${_index})
        string(JSON _enum_value GET "${schema_json}" enum ${_index})
        if(instance_type STREQUAL _enum_type AND instance_value STREQUAL _enum_value)
          set(_enum_match TRUE)
        endif()
      endforeach()
    endif()
    if(NOT _enum_match)
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: value is not in schema enum" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_pattern "${schema_json}" pattern)
  if(_has_pattern AND instance_type STREQUAL "STRING")
    string(JSON _pattern GET "${schema_json}" pattern)
    if(NOT "${instance_value}" MATCHES "${_pattern}")
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: string does not match '${_pattern}'" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_min_length "${schema_json}" minLength)
  if(_has_min_length AND instance_type STREQUAL "STRING")
    string(JSON _minimum GET "${schema_json}" minLength)
    string(LENGTH "${instance_value}" _actual_length)
    if(_actual_length LESS _minimum)
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: string is shorter than minLength" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_all_of "${schema_json}" allOf)
  if(_has_all_of)
    string(JSON _all_length LENGTH "${schema_json}" allOf)
    if(_all_length GREATER 0)
      math(EXPR _all_last "${_all_length} - 1")
      foreach(_index RANGE 0 ${_all_last})
        string(JSON _subschema GET "${schema_json}" allOf ${_index})
        _schema_validate_node(_valid _error "${instance_value}" "${instance_type}" "${_subschema}" "${root_schema}" "${context}/allOf/${_index}")
        if(NOT _valid)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${_error}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
    endif()
  endif()

  _json_has(_has_not "${schema_json}" not)
  if(_has_not)
    string(JSON _not_schema GET "${schema_json}" not)
    _schema_validate_node(_not_valid _not_error "${instance_value}" "${instance_type}" "${_not_schema}" "${root_schema}" "${context}/not")
    if(_not_valid)
      set(${out_valid} FALSE PARENT_SCOPE)
      set(${out_error} "${context}: value matches forbidden schema" PARENT_SCOPE)
      return()
    endif()
  endif()

  _json_has(_has_if "${schema_json}" if)
  if(_has_if)
    string(JSON _if_schema GET "${schema_json}" if)
    _schema_validate_node(_if_valid _if_error "${instance_value}" "${instance_type}" "${_if_schema}" "${root_schema}" "${context}/if")
    if(_if_valid)
      _json_has(_has_then "${schema_json}" then)
      if(_has_then)
        string(JSON _then_schema GET "${schema_json}" then)
        _schema_validate_node(_then_valid _then_error "${instance_value}" "${instance_type}" "${_then_schema}" "${root_schema}" "${context}/then")
        if(NOT _then_valid)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${_then_error}" PARENT_SCOPE)
          return()
        endif()
      endif()
    else()
      _json_has(_has_else "${schema_json}" else)
      if(_has_else)
        string(JSON _else_schema GET "${schema_json}" else)
        _schema_validate_node(_else_valid _else_error "${instance_value}" "${instance_type}" "${_else_schema}" "${root_schema}" "${context}/else")
        if(NOT _else_valid)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${_else_error}" PARENT_SCOPE)
          return()
        endif()
      endif()
    endif()
  endif()

  if(instance_type STREQUAL "OBJECT")
    _json_has(_has_required "${schema_json}" required)
    if(_has_required)
      string(JSON _required_length LENGTH "${schema_json}" required)
      if(_required_length GREATER 0)
        math(EXPR _required_last "${_required_length} - 1")
        foreach(_index RANGE 0 ${_required_last})
          string(JSON _required_name GET "${schema_json}" required ${_index})
          _json_has(_member_present "${instance_value}" "${_required_name}")
          if(NOT _member_present)
            set(${out_valid} FALSE PARENT_SCOPE)
            set(${out_error} "${context}: missing required property '${_required_name}'" PARENT_SCOPE)
            return()
          endif()
        endforeach()
      endif()
    endif()

    string(JSON _member_count LENGTH "${instance_value}")
    if(_member_count GREATER 0)
      math(EXPR _member_last "${_member_count} - 1")
      foreach(_index RANGE 0 ${_member_last})
        string(JSON _member_name MEMBER "${instance_value}" ${_index})
        _json_has(_property_declared "${schema_json}" properties "${_member_name}")
        if(_property_declared)
          string(JSON _property_schema GET "${schema_json}" properties "${_member_name}")
          string(JSON _child_type TYPE "${instance_value}" "${_member_name}")
          string(JSON _child_value GET "${instance_value}" "${_member_name}")
          _schema_validate_node(_valid _error "${_child_value}" "${_child_type}" "${_property_schema}" "${root_schema}" "${context}/${_member_name}")
          if(NOT _valid)
            set(${out_valid} FALSE PARENT_SCOPE)
            set(${out_error} "${_error}" PARENT_SCOPE)
            return()
          endif()
        else()
          _json_has(_has_additional "${schema_json}" additionalProperties)
          if(_has_additional)
            string(JSON _additional GET "${schema_json}" additionalProperties)
            if(NOT _additional)
              set(${out_valid} FALSE PARENT_SCOPE)
              set(${out_error} "${context}: undeclared property '${_member_name}'" PARENT_SCOPE)
              return()
            endif()
          endif()
        endif()
      endforeach()
    endif()
  elseif(instance_type STREQUAL "ARRAY")
    string(JSON _item_count LENGTH "${instance_value}")
    foreach(_bound IN ITEMS minItems maxItems)
      _json_has(_has_bound "${schema_json}" ${_bound})
      if(_has_bound)
        string(JSON _bound_value GET "${schema_json}" ${_bound})
        if(_bound STREQUAL "minItems" AND _item_count LESS _bound_value)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${context}: array violates minItems" PARENT_SCOPE)
          return()
        elseif(_bound STREQUAL "maxItems" AND _item_count GREATER _bound_value)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${context}: array violates maxItems" PARENT_SCOPE)
          return()
        endif()
      endif()
    endforeach()
    _json_has(_has_unique "${schema_json}" uniqueItems)
    if(_has_unique)
      string(JSON _unique GET "${schema_json}" uniqueItems)
      if(_unique AND _item_count GREATER 1)
        math(EXPR _item_last "${_item_count} - 1")
        foreach(_left RANGE 0 ${_item_last})
          string(JSON _left_value GET "${instance_value}" ${_left})
          math(EXPR _right_first "${_left} + 1")
          if(_right_first LESS_EQUAL _item_last)
            foreach(_right RANGE ${_right_first} ${_item_last})
              string(JSON _right_value GET "${instance_value}" ${_right})
              if(_left_value STREQUAL _right_value)
                set(${out_valid} FALSE PARENT_SCOPE)
                set(${out_error} "${context}: array violates uniqueItems" PARENT_SCOPE)
                return()
              endif()
            endforeach()
          endif()
        endforeach()
      endif()
    endif()
    _json_has(_has_items "${schema_json}" items)
    if(_has_items AND _item_count GREATER 0)
      string(JSON _item_schema GET "${schema_json}" items)
      math(EXPR _item_last "${_item_count} - 1")
      foreach(_index RANGE 0 ${_item_last})
        string(JSON _child_type TYPE "${instance_value}" ${_index})
        string(JSON _child_value GET "${instance_value}" ${_index})
        _schema_validate_node(_valid _error "${_child_value}" "${_child_type}" "${_item_schema}" "${root_schema}" "${context}/${_index}")
        if(NOT _valid)
          set(${out_valid} FALSE PARENT_SCOPE)
          set(${out_error} "${_error}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
    endif()
  endif()

  set(${out_valid} TRUE PARENT_SCOPE)
  set(${out_error} "" PARENT_SCOPE)
endfunction()

function(_schema_validate out_valid out_error instance_json schema_json context)
  string(JSON _instance_type ERROR_VARIABLE _instance_error TYPE "${instance_json}")
  if(NOT _instance_error STREQUAL "NOTFOUND")
    set(${out_valid} FALSE PARENT_SCOPE)
    set(${out_error} "${context}: invalid instance JSON: ${_instance_error}" PARENT_SCOPE)
    return()
  endif()
  _schema_validate_node(_valid _error "${instance_json}" "${_instance_type}" "${schema_json}" "${schema_json}" "${context}")
  set(${out_valid} "${_valid}" PARENT_SCOPE)
  set(${out_error} "${_error}" PARENT_SCOPE)
endfunction()

function(_expect_schema_invalid label instance_json schema_json)
  _schema_validate(_valid _error "${instance_json}" "${schema_json}" "${label}")
  if(_valid)
    _fail("mutation '${label}' unexpectedly passed its Draft 2020-12 schema")
  endif()
endfunction()

function(_array_contains json_text expected)
  string(JSON _length ERROR_VARIABLE _error LENGTH "${json_text}" ${ARGN})
  if(NOT _error STREQUAL "NOTFOUND")
    _fail("missing JSON array '${ARGN}': ${_error}")
  endif()
  set(_found FALSE)
  if(_length GREATER 0)
    math(EXPR _last "${_length} - 1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _value GET "${json_text}" ${ARGN} ${_index})
      if(_value STREQUAL "${expected}")
        set(_found TRUE)
      endif()
    endforeach()
  endif()
  if(NOT _found)
    _fail("JSON array '${ARGN}' lacks required value '${expected}'")
  endif()
endfunction()

function(_is_within_resolved_tree out tree_path candidate_path)
  file(TO_CMAKE_PATH "${tree_path}" _tree_path)
  file(TO_CMAKE_PATH "${candidate_path}" _candidate_path)
  if(_candidate_path STREQUAL _tree_path)
    set(${out} TRUE PARENT_SCOPE)
    return()
  endif()
  set(_tree_prefix "${_tree_path}/")
  string(FIND "${_candidate_path}" "${_tree_prefix}" _prefix_index)
  if(_prefix_index EQUAL 0)
    set(${out} TRUE PARENT_SCOPE)
  else()
    set(${out} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_portable_relative_path path_value case_root)
  if(path_value STREQUAL "" OR IS_ABSOLUTE "${path_value}")
    _fail("path is empty or absolute: '${path_value}'")
  endif()
  if(path_value MATCHES "(^|/)\\.\\.(/|$)" OR path_value MATCHES "\\\\" OR path_value MATCHES "//")
    _fail("path contains traversal, backslash, or an empty segment: '${path_value}'")
  endif()
  string(TOUPPER "${path_value}" _upper_path)
  if(_upper_path MATCHES "(^|/)(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\\.|/|$)")
    _fail("path contains a reserved Windows device name: '${path_value}'")
  endif()
  if(NOT EXISTS "${case_root}/${path_value}")
    _fail("declared case path does not exist: '${path_value}'")
  endif()
  file(REAL_PATH "${case_root}" _root_real)
  file(REAL_PATH "${case_root}/${path_value}" _path_real)
  _is_within_resolved_tree(_path_inside "${_root_real}" "${_path_real}")
  if(NOT _path_inside)
    _fail("declared path escapes its case root after resolution: '${path_value}'")
  endif()
endfunction()

function(_assert_tree_safety tree_root)
  if(NOT IS_DIRECTORY "${tree_root}")
    _fail("missing contract tree: ${tree_root}")
  endif()
  file(REAL_PATH "${tree_root}" _tree_real)
  file(TO_CMAKE_PATH "${_tree_real}" _tree_real)
  file(GLOB_RECURSE _entries LIST_DIRECTORIES TRUE "${tree_root}/*")
  list(PREPEND _entries "${tree_root}")
  set(_casefold_paths)
  foreach(_entry IN LISTS _entries)
    if(IS_SYMLINK "${_entry}")
      _fail("symbolic link is forbidden in contract inventory: ${_entry}")
    endif()
    file(REAL_PATH "${_entry}" _entry_real)
    _is_within_resolved_tree(_entry_inside "${_tree_real}" "${_entry_real}")
    if(NOT _entry_inside)
      _fail("inventory entry escapes its tree after resolution: ${_entry}")
    endif()
    file(RELATIVE_PATH _relative "${tree_root}" "${_entry}")
    string(TOUPPER "${_relative}" _casefold)
    list(FIND _casefold_paths "${_casefold}" _collision_index)
    if(NOT _collision_index EQUAL -1)
      _fail("case-insensitive path collision in contract inventory: ${_relative}")
    endif()
    list(APPEND _casefold_paths "${_casefold}")

    if(WIN32)
      execute_process(COMMAND fsutil reparsepoint query "${_entry}" RESULT_VARIABLE _reparse_result OUTPUT_QUIET ERROR_QUIET)
      if(_reparse_result EQUAL 0)
        _fail("junction or other reparse point is forbidden in contract inventory: ${_entry}")
      endif()
      if(NOT IS_DIRECTORY "${_entry}")
        execute_process(COMMAND fsutil hardlink list "${_entry}" RESULT_VARIABLE _hardlink_result OUTPUT_VARIABLE _hardlinks ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT _hardlink_result EQUAL 0)
          _fail("cannot certify hardlink state for contract file: ${_entry}")
        endif()
        string(REPLACE "\r\n" "\n" _hardlinks "${_hardlinks}")
        string(REPLACE "\n" ";" _hardlink_list "${_hardlinks}")
        list(FILTER _hardlink_list EXCLUDE REGEX "^$")
        list(LENGTH _hardlink_list _hardlink_count)
        if(_hardlink_count GREATER 1)
          _fail("hardlinked contract file is forbidden: ${_entry}")
        endif()
      endif()
    endif()
  endforeach()
endfunction()

set(_schema_inventory
  README.md
  acceptance.schema.json
  case-config-envelope.schema.json
  case-manifest.schema.json
  media-manifest.schema.json
  reference-manifest.schema.json
  run-manifest.schema.json
  verification-result.schema.json)
file(GLOB_RECURSE _actual_schema_inventory RELATIVE "${_contracts}" LIST_DIRECTORIES FALSE "${_contracts}/*")
list(SORT _schema_inventory)
list(SORT _actual_schema_inventory)
if(NOT _actual_schema_inventory STREQUAL _schema_inventory)
  _fail("contract schema inventory differs; actual='${_actual_schema_inventory}', expected='${_schema_inventory}'")
endif()
_assert_tree_safety("${_contracts}")

set(_schema_names case-manifest case-config-envelope acceptance reference-manifest run-manifest verification-result media-manifest)
foreach(_schema_name IN LISTS _schema_names)
  _read_json(_schema "${_contracts}/${_schema_name}.schema.json")
  _json_equal("${_schema}" "urn:nexilb:schema:${_schema_name}:1.0" \$id)
  _json_equal("${_schema}" "https://json-schema.org/draft/2020-12/schema" \$schema)
  _json_equal("${_schema}" "OFF" additionalProperties)
  string(REPLACE "-" "_" _schema_variable "${_schema_name}")
  set("_schema_${_schema_variable}" "${_schema}")
endforeach()

set(_cases nphase-wetting-minimal imb-coupling-minimal dem-contact-restart pure-coupled-degeneration)
set(_case_inventory
  CMakeLists.txt
  README.md
  case-manifest.json
  case.json
  contract-state/media-manifest.json
  contract-state/run-manifest.json
  contract-state/verification-result.json
  expected/acceptance.json
  expected/reference-manifest.json)
list(SORT _case_inventory)
set(_schema_application_count 0)
set(_mutation_count 0)
set(_applied_schema_ids)

foreach(_case_id IN LISTS _cases)
  set(_case_root "${_examples}/${_case_id}")
  if(_case_id STREQUAL "nphase-wetting-minimal")
    set(_contract_case_id "CASE-NPHASE-WETTING-MINIMAL")
  elseif(_case_id STREQUAL "imb-coupling-minimal")
    set(_contract_case_id "CASE-IMB-COUPLING-MINIMAL")
  elseif(_case_id STREQUAL "dem-contact-restart")
    set(_contract_case_id "CASE-DEM-CONTACT-RESTART")
  else()
    set(_contract_case_id "CASE-PURE-COUPLED-DEGENERATION")
  endif()
  _assert_tree_safety("${_case_root}")
  file(GLOB_RECURSE _actual_case_inventory RELATIVE "${_case_root}" LIST_DIRECTORIES FALSE "${_case_root}/*")
  list(SORT _actual_case_inventory)
  if(NOT _actual_case_inventory STREQUAL _case_inventory)
    _fail("${_case_id} inventory differs; actual='${_actual_case_inventory}', expected='${_case_inventory}'")
  endif()

  foreach(_relative_json IN ITEMS case-manifest.json case.json expected/acceptance.json expected/reference-manifest.json contract-state/run-manifest.json contract-state/verification-result.json contract-state/media-manifest.json)
    _read_json(_document "${_case_root}/${_relative_json}")
    _json_equal("${_document}" "${_contract_case_id}" case_id)
    if(_relative_json STREQUAL "case-manifest.json")
      set(_document_schema "${_schema_case_manifest}")
    elseif(_relative_json STREQUAL "case.json")
      set(_document_schema "${_schema_case_config_envelope}")
    elseif(_relative_json STREQUAL "expected/acceptance.json")
      set(_document_schema "${_schema_acceptance}")
    elseif(_relative_json STREQUAL "expected/reference-manifest.json")
      set(_document_schema "${_schema_reference_manifest}")
    elseif(_relative_json STREQUAL "contract-state/run-manifest.json")
      set(_document_schema "${_schema_run_manifest}")
    elseif(_relative_json STREQUAL "contract-state/verification-result.json")
      set(_document_schema "${_schema_verification_result}")
    else()
      set(_document_schema "${_schema_media_manifest}")
    endif()
    _schema_validate(_schema_valid _schema_error "${_document}" "${_document_schema}" "${_case_id}/${_relative_json}")
    if(NOT _schema_valid)
      _fail("${_case_id}/${_relative_json} failed its Draft 2020-12 schema: ${_schema_error}")
    endif()
    math(EXPR _schema_application_count "${_schema_application_count} + 1")
    string(JSON _applied_schema_id GET "${_document_schema}" \$id)
    list(APPEND _applied_schema_ids "${_applied_schema_id}")

    string(JSON _unknown_property_mutation SET "${_document}" mutation_probe "\"unexpected\"")
    _expect_schema_invalid("${_case_id}/${_relative_json}:additionalProperties" "${_unknown_property_mutation}" "${_document_schema}")
    string(JSON _missing_required_mutation REMOVE "${_document}" \$schema)
    _expect_schema_invalid("${_case_id}/${_relative_json}:required" "${_missing_required_mutation}" "${_document_schema}")
    math(EXPR _mutation_count "${_mutation_count} + 2")

    if(_relative_json STREQUAL "case-manifest.json" OR _relative_json STREQUAL "contract-state/run-manifest.json")
      if(_case_id STREQUAL "pure-coupled-degeneration")
        string(JSON _wrong_model_mutation REMOVE "${_document}" model_ids 1)
      elseif(_case_id STREQUAL "nphase-wetting-minimal")
        string(JSON _wrong_model_mutation SET "${_document}" model_ids 0 "\"model.NPhaseImbDemContactAngle\"")
      else()
        string(JSON _wrong_model_mutation SET "${_document}" model_ids 0 "\"model.NPhaseContactAngle\"")
      endif()
      _expect_schema_invalid("${_case_id}/${_relative_json}:wrong-model" "${_wrong_model_mutation}" "${_document_schema}")
      math(EXPR _mutation_count "${_mutation_count} + 1")
    elseif(_relative_json STREQUAL "case.json")
      if(_case_id STREQUAL "pure-coupled-degeneration")
        string(JSON _wrong_model_mutation REMOVE "${_document}" model_configs 1)
      elseif(_case_id STREQUAL "nphase-wetting-minimal")
        string(JSON _wrong_model_mutation SET "${_document}" model_configs 0 model_id "\"model.NPhaseImbDemContactAngle\"")
      else()
        string(JSON _wrong_model_mutation SET "${_document}" model_configs 0 model_id "\"model.NPhaseContactAngle\"")
      endif()
      _expect_schema_invalid("${_case_id}/${_relative_json}:wrong-model" "${_wrong_model_mutation}" "${_document_schema}")
      math(EXPR _mutation_count "${_mutation_count} + 1")
    endif()
  endforeach()

  _read_json(_manifest "${_case_root}/case-manifest.json")
  _json_equal("${_manifest}" "urn:nexilb:schema:case-manifest:1.0" \$schema)
  _json_equal("${_manifest}" "implementation_not_present" contract_state implementation)
  _json_equal("${_manifest}" "runtime_unavailable" contract_state runtime)
  _json_equal("${_manifest}" "verification_not_evaluated" contract_state verification)
  string(JSON _asset_count LENGTH "${_manifest}" required_assets)
  string(JSON _capability_count LENGTH "${_manifest}" required_capabilities)
  string(JSON _test_count LENGTH "${_manifest}" blocking_test_ids)
  string(JSON _validation_count LENGTH "${_manifest}" blocking_validation_ids)
  if(_asset_count LESS 1 OR _capability_count LESS 1 OR _test_count LESS 1 OR _validation_count LESS 1)
    _fail("${_case_id} must declare assets, capabilities, TST blockers, and VAL blockers")
  endif()
  math(EXPR _asset_last "${_asset_count} - 1")
  foreach(_index RANGE 0 ${_asset_last})
    _json_equal("${_manifest}" "required_not_present" required_assets ${_index} status)
  endforeach()
  math(EXPR _capability_last "${_capability_count} - 1")
  foreach(_index RANGE 0 ${_capability_last})
    _json_equal("${_manifest}" "required_unavailable" required_capabilities ${_index} status)
  endforeach()

  foreach(_path_key IN ITEMS case_config acceptance reference_manifest run_manifest verification_result media_manifest)
    if(_path_key STREQUAL "case_config")
      set(_expected_path "case.json")
    elseif(_path_key STREQUAL "acceptance")
      set(_expected_path "expected/acceptance.json")
    elseif(_path_key STREQUAL "reference_manifest")
      set(_expected_path "expected/reference-manifest.json")
    elseif(_path_key STREQUAL "run_manifest")
      set(_expected_path "contract-state/run-manifest.json")
    elseif(_path_key STREQUAL "verification_result")
      set(_expected_path "contract-state/verification-result.json")
    else()
      set(_expected_path "contract-state/media-manifest.json")
    endif()
    string(JSON _path GET "${_manifest}" paths ${_path_key})
    if(NOT _path STREQUAL _expected_path)
      _fail("${_case_id} path '${_path_key}' is '${_path}', expected '${_expected_path}'")
    endif()
    _portable_relative_path("${_path}" "${_case_root}")
  endforeach()
  foreach(_unsafe_path IN ITEMS "../case.json" "C:/case.json" "con/input.json" "nested//case.json")
    string(JSON _unsafe_path_mutation SET "${_manifest}" paths case_config "\"${_unsafe_path}\"")
    _expect_schema_invalid("${_case_id}:unsafe-path:${_unsafe_path}" "${_unsafe_path_mutation}" "${_schema_case_manifest}")
    math(EXPR _mutation_count "${_mutation_count} + 1")
  endforeach()

  _read_json(_config "${_case_root}/case.json")
  _json_equal("${_config}" "urn:nexilb:schema:case-config-envelope:1.0" \$schema)
  _json_equal("${_config}" "implementation_not_present" contract_state implementation)
  _json_equal("${_config}" "runtime_unavailable" contract_state runtime)
  _json_equal("${_config}" "verification_not_evaluated" contract_state verification)

  _read_json(_acceptance "${_case_root}/expected/acceptance.json")
  _json_equal("${_acceptance}" "urn:nexilb:schema:acceptance:1.0" \$schema)
  _json_equal("${_acceptance}" "verification_not_evaluated" verification_status)
  string(JSON _criterion_count LENGTH "${_acceptance}" criteria)
  if(_criterion_count LESS 1)
    _fail("${_case_id} has no case-specific acceptance criterion")
  endif()
  math(EXPR _criterion_last "${_criterion_count} - 1")
  foreach(_index RANGE 0 ${_criterion_last})
    _json_equal("${_acceptance}" "approval_required" criteria ${_index} comparator_status)
    _json_equal("${_acceptance}" "not_specified" criteria ${_index} tolerance_status)
    _json_equal("${_acceptance}" "verification_not_evaluated" criteria ${_index} evaluation_status)
  endforeach()

  _read_json(_reference "${_case_root}/expected/reference-manifest.json")
  _json_equal("${_reference}" "urn:nexilb:schema:reference-manifest:1.0" \$schema)
  _json_equal("${_reference}" "required_not_present" reference_status)
  string(JSON _reference_count LENGTH "${_reference}" references)
  if(_reference_count LESS 1)
    _fail("${_case_id} must declare required reference artifacts")
  endif()
  math(EXPR _reference_last "${_reference_count} - 1")
  foreach(_index RANGE 0 ${_reference_last})
    _json_equal("${_reference}" "required_not_present" references ${_index} status)
  endforeach()

  _read_json(_run "${_case_root}/contract-state/run-manifest.json")
  _json_equal("${_run}" "urn:nexilb:schema:run-manifest:1.0" \$schema)
  _json_equal("${_run}" "implementation_not_present" implementation_status)
  _json_equal("${_run}" "runtime_unavailable" execution_status)
  string(JSON _run_status_mutation SET "${_run}" execution_status "\"success\"")
  _expect_schema_invalid("${_case_id}:false-success-status" "${_run_status_mutation}" "${_schema_run_manifest}")
  math(EXPR _mutation_count "${_mutation_count} + 1")
  string(JSON _output_count LENGTH "${_run}" outputs)
  if(NOT _output_count EQUAL 0)
    _fail("${_case_id} contract-only run manifest must contain no outputs")
  endif()

  _read_json(_verification "${_case_root}/contract-state/verification-result.json")
  _json_equal("${_verification}" "urn:nexilb:schema:verification-result:1.0" \$schema)
  _json_equal("${_verification}" "verification_not_evaluated" verification_status)
  _json_equal("${_verification}" "runtime_unavailable" reason)

  _read_json(_media "${_case_root}/contract-state/media-manifest.json")
  _json_equal("${_media}" "urn:nexilb:schema:media-manifest:1.0" \$schema)
  _json_equal("${_media}" "not_generated" media_status)
  _json_equal("${_media}" "verification_not_evaluated" gate_status)
  string(JSON _media_count LENGTH "${_media}" artifacts)
  if(NOT _media_count EQUAL 0)
    _fail("${_case_id} contract-only media manifest must contain no artifacts")
  endif()

  if(_case_id STREQUAL "nphase-wetting-minimal")
    set(_expected_models model.NPhaseContactAngle)
    _array_contains("${_config}" "REQ-NPHASE-COUNT-AT-LEAST-THREE" semantic_requirements)
    _array_contains("${_manifest}" "TST-NPHASE-MAX-PLUS-ONE-REJECTED" blocking_test_ids)
    _array_contains("${_manifest}" "VAL-WETTING-CONTACT-ANGLE" blocking_validation_ids)
    _json_equal("${_acceptance}" "metric.wetting.contact_angle" criteria 2 metric_id)
  elseif(_case_id STREQUAL "imb-coupling-minimal")
    set(_expected_models model.NPhaseImbDemContactAngle)
    _array_contains("${_config}" "REQ-CONTACT-ZERO-EVERY-SNAPSHOT" semantic_requirements)
    _array_contains("${_config}" "REQ-FORCE-HYDRODYNAMIC-COMPONENT-ISOLATED" semantic_requirements)
    _array_contains("${_manifest}" "TST-IMB-ZERO-CONTACT-EVERY-SNAPSHOT" blocking_test_ids)
    _array_contains("${_manifest}" "VAL-IMB-HYDRODYNAMIC-FORCE-TORQUE" blocking_validation_ids)
  elseif(_case_id STREQUAL "dem-contact-restart")
    set(_expected_models model.NPhaseImbDemContactAngle)
    _array_contains("${_config}" "REQ-CONTACT-PARTICLE-PARTICLE-AND-PARTICLE-WALL" semantic_requirements)
    _array_contains("${_config}" "REQ-CHECKPOINT-PUBLIC-HISTORY-NONZERO" semantic_requirements)
    _array_contains("${_config}" "REQ-CHECKPOINT-FOUR-ISOLATED-PROCESSES" semantic_requirements)
    _array_contains("${_manifest}" "TST-DEM-ZERO-HISTORY-REJECTED" blocking_test_ids)
    _array_contains("${_manifest}" "VAL-DEM-RESTART-CONTINUITY" blocking_validation_ids)
  else()
    set(_expected_models model.NPhaseContactAngle model.NPhaseImbDemContactAngle)
    _array_contains("${_config}" "REQ-CONFIGURATION-TWO-INDEPENDENT-DOCUMENTS" semantic_requirements)
    _array_contains("${_config}" "REQ-COUPLED-ZERO-PARTICLES-AND-COUPLING-ENABLED" semantic_requirements)
    _array_contains("${_config}" "REQ-PURE-IMB-EXPLICITLY-DISABLED" semantic_requirements)
    _array_contains("${_manifest}" "TST-DEGENERATION-NONZERO-PARTICLE-REJECTED" blocking_test_ids)
    _array_contains("${_manifest}" "TST-DEGENERATION-NONZERO-IMB-REJECTED" blocking_test_ids)
    _array_contains("${_manifest}" "VAL-DEGENERATION-FIELD-DESCRIPTOR-IDENTITY" blocking_validation_ids)
    _array_contains("${_manifest}" "VAL-DEGENERATION-INVALID-INPUT-REJECTION" blocking_validation_ids)
    _array_contains("${_acceptance}" "VAL-DEGENERATION-INVALID-INPUT-REJECTION" criteria 3 evidence_ids)
    _json_equal("${_reference}" "VAL-DEGENERATION-INVALID-INPUT-REJECTION" references 3 required_evidence_ids 0)
  endif()

  string(JSON _manifest_model_count LENGTH "${_manifest}" model_ids)
  string(JSON _config_model_count LENGTH "${_config}" model_configs)
  list(LENGTH _expected_models _expected_model_count)
  if(NOT _manifest_model_count EQUAL _expected_model_count OR NOT _config_model_count EQUAL _expected_model_count)
    _fail("${_case_id} has an incorrect model count")
  endif()
  math(EXPR _model_last "${_expected_model_count} - 1")
  foreach(_index RANGE 0 ${_model_last})
    list(GET _expected_models ${_index} _expected_model)
    _json_equal("${_manifest}" "${_expected_model}" model_ids ${_index})
    _json_equal("${_config}" "${_expected_model}" model_configs ${_index} model_id)
    _json_equal("${_run}" "${_expected_model}" model_ids ${_index})
  endforeach()
endforeach()

list(REMOVE_DUPLICATES _applied_schema_ids)
list(SORT _applied_schema_ids)
set(_expected_schema_ids
  urn:nexilb:schema:acceptance:1.0
  urn:nexilb:schema:case-config-envelope:1.0
  urn:nexilb:schema:case-manifest:1.0
  urn:nexilb:schema:media-manifest:1.0
  urn:nexilb:schema:reference-manifest:1.0
  urn:nexilb:schema:run-manifest:1.0
  urn:nexilb:schema:verification-result:1.0)
list(SORT _expected_schema_ids)
if(NOT _applied_schema_ids STREQUAL _expected_schema_ids)
  _fail("schema application coverage differs; actual='${_applied_schema_ids}', expected='${_expected_schema_ids}'")
endif()
if(NOT _schema_application_count EQUAL 28 OR NOT _mutation_count EQUAL 88)
  _fail("unexpected validation coverage: ${_schema_application_count} applications, ${_mutation_count} mutations")
endif()

file(GLOB_RECURSE _all_json LIST_DIRECTORIES FALSE "${_contracts}/*.json" "${_examples}/*.json")
foreach(_json_file IN LISTS _all_json)
  _read_json(_unused "${_json_file}")
endforeach()

message(STATUS "Applied all 7 Draft 2020-12 schemas to 28 instances; 88 mutation negatives rejected; evidence, model mapping, inventory, and link safety passed")
