function(_nexilb_assert_regular_contained artifact_file package_prefix label)
  if(NOT EXISTS "${artifact_file}" OR IS_DIRECTORY "${artifact_file}")
    message(FATAL_ERROR "${label} is missing or is not a regular file: ${artifact_file}")
  endif()
  if(IS_SYMLINK "${artifact_file}")
    message(FATAL_ERROR "${label} must not be a symbolic link: ${artifact_file}")
  endif()

  file(REAL_PATH "${package_prefix}" package_prefix_real)
  file(REAL_PATH "${artifact_file}" artifact_file_real)
  string(REPLACE "\\" "/" package_prefix_real "${package_prefix_real}")
  string(REPLACE "\\" "/" artifact_file_real "${artifact_file_real}")
  string(TOLOWER "${package_prefix_real}" package_prefix_key)
  string(TOLOWER "${artifact_file_real}" artifact_file_key)
  string(FIND "${artifact_file_key}" "${package_prefix_key}/" contained_position)
  if(NOT contained_position EQUAL 0)
    message(FATAL_ERROR "${label} resolves outside the package prefix")
  endif()

  get_filename_component(cursor "${artifact_file}" DIRECTORY)
  while(TRUE)
    if(IS_SYMLINK "${cursor}")
      message(FATAL_ERROR "${label} traverses a symbolic-link directory: ${cursor}")
    endif()
    if(cursor STREQUAL package_prefix)
      break()
    endif()
    get_filename_component(parent "${cursor}" DIRECTORY)
    if(parent STREQUAL cursor)
      message(FATAL_ERROR "${label} is not lexically contained in the package prefix")
    endif()
    set(cursor "${parent}")
  endwhile()
endfunction()

function(_nexilb_assert_imported_location target artifact_file label)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "${label} imported target is missing: ${target}")
  endif()
  set(_locations)
  get_target_property(_configurations "${target}" IMPORTED_CONFIGURATIONS)
  foreach(_configuration IN LISTS _configurations)
    string(TOUPPER "${_configuration}" _configuration_upper)
    get_target_property(_location "${target}"
      "IMPORTED_LOCATION_${_configuration_upper}")
    if(_location AND EXISTS "${_location}")
      file(REAL_PATH "${_location}" _location_real)
      list(APPEND _locations "${_location_real}")
    endif()
  endforeach()
  get_target_property(_location "${target}" IMPORTED_LOCATION)
  if(_location AND EXISTS "${_location}")
    file(REAL_PATH "${_location}" _location_real)
    list(APPEND _locations "${_location_real}")
  endif()
  list(REMOVE_DUPLICATES _locations)
  file(REAL_PATH "${artifact_file}" _artifact_real)
  if(NOT _artifact_real IN_LIST _locations)
    message(FATAL_ERROR
      "${label} manifest path does not match ${target}")
  endif()
endfunction()

function(_nexilb_verify_package_manifest manifest_file)
  if(NOT EXISTS "${manifest_file}")
    message(FATAL_ERROR "NexiLB package manifest is missing: ${manifest_file}")
  endif()
  file(READ "${manifest_file}" manifest_json)
  string(JSON schema ERROR_VARIABLE json_error
    GET "${manifest_json}" schema_version)
  string(JSON schema_id ERROR_VARIABLE schema_id_error
    GET "${manifest_json}" schema_id)
  if(json_error OR schema_id_error OR NOT schema EQUAL 4 OR
     NOT schema_id STREQUAL "urn:nexilb:runtime-manifest:4")
    message(FATAL_ERROR "Unsupported NexiLB package manifest schema")
  endif()
  string(JSON package_state GET "${manifest_json}" package_state)
  string(JSON sdk_version GET "${manifest_json}" sdk_version)
  string(JSON abi_major GET "${manifest_json}" abi major)
  string(JSON abi_minor GET "${manifest_json}" abi minor)
  string(JSON api_min GET "${manifest_json}" api min)
  string(JSON api_max GET "${manifest_json}" api max)
  string(JSON runtime_load_name GET
    "${manifest_json}" runtime_load_name)
  string(JSON expected_artifact_set_sha256 GET
    "${manifest_json}" artifact_set_sha256)
  string(LENGTH "${expected_artifact_set_sha256}"
    expected_artifact_set_sha256_length)
  if(NOT sdk_version STREQUAL NexiLB_SDK_VERSION OR
     NOT abi_major EQUAL NexiLB_ABI_MAJOR OR NOT abi_minor EQUAL 0 OR
     NOT api_min EQUAL NexiLB_API_VERSION OR
     NOT api_max EQUAL NexiLB_API_VERSION)
    message(FATAL_ERROR "NexiLB package manifest version mismatch")
  endif()
  if(NOT package_state STREQUAL "release")
    message(FATAL_ERROR "Unsupported NexiLB package state")
  endif()  if(runtime_load_name MATCHES "[/\\\\]" OR
     NOT runtime_load_name MATCHES "^[A-Za-z0-9._+-]+$")
    message(FATAL_ERROR "Invalid NexiLB runtime load name")
  endif()
  if(NOT expected_artifact_set_sha256_length EQUAL 64 OR
     expected_artifact_set_sha256 MATCHES "[^0-9a-f]")
    message(FATAL_ERROR "Invalid NexiLB artifact-set hash")
  endif()

  get_filename_component(manifest_dir "${manifest_file}" DIRECTORY)
  get_filename_component(share_dir "${manifest_dir}" DIRECTORY)
  get_filename_component(package_prefix "${share_dir}" DIRECTORY)
  _nexilb_assert_regular_contained(
    "${manifest_file}" "${package_prefix}" "NexiLB package manifest")
  string(JSON artifact_count LENGTH "${manifest_json}" artifacts)
  if(NOT artifact_count EQUAL 7)
    message(FATAL_ERROR
      "NexiLB runtime manifest must contain exactly seven package artifacts")
  endif()

  set(seen_roles)
  set(seen_paths)
  set(expected_roles runtime case_verify case_test public_header public_cpp_header abi_layout catalog_bundle)
  set(artifact_identity "runtime_load_name|${runtime_load_name}\n")
  math(EXPR last_artifact "${artifact_count} - 1")
  foreach(index RANGE 0 ${last_artifact})
    string(JSON role GET "${manifest_json}" artifacts ${index} role)
    string(JSON relative_path GET "${manifest_json}" artifacts ${index} path)
    string(JSON expected_size GET "${manifest_json}" artifacts ${index} size)
    string(JSON expected_size_type TYPE "${manifest_json}" artifacts ${index} size)
    string(JSON expected_sha256 GET "${manifest_json}" artifacts ${index} sha256)
    string(LENGTH "${expected_sha256}" expected_sha256_length)
    set(normalized_path "${relative_path}")
    cmake_path(NORMAL_PATH normalized_path)
    string(TOLOWER "${normalized_path}" normalized_path_key)
    list(GET expected_roles ${index} expected_role)
    string(TOUPPER "${relative_path}" upper_relative_path)
    if(NOT role STREQUAL expected_role OR
       role IN_LIST seen_roles OR normalized_path_key IN_LIST seen_paths OR
       IS_ABSOLUTE "${relative_path}" OR
       relative_path MATCHES "\\\\" OR
       relative_path MATCHES "(^|/)\\.\\.?(/|$)" OR
       relative_path MATCHES "//" OR
       NOT relative_path MATCHES "^[A-Za-z0-9._/-]+$" OR
       upper_relative_path MATCHES "(^|/)(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\\.|/|$)" OR
       NOT normalized_path STREQUAL relative_path OR
       NOT expected_size_type STREQUAL "NUMBER" OR
       NOT expected_size MATCHES "^(0|[1-9][0-9]*)$" OR
       NOT expected_sha256_length EQUAL 64 OR
       expected_sha256 MATCHES "[^0-9a-f]")
      message(FATAL_ERROR "Invalid or duplicate NexiLB manifest artifact")
    endif()
    list(APPEND seen_roles "${role}")
    list(APPEND seen_paths "${normalized_path_key}")
    string(APPEND artifact_identity
      "${role}|${relative_path}|${expected_size}|${expected_sha256}\n")
    set(artifact_file "${package_prefix}/${relative_path}")
    _nexilb_assert_regular_contained(
      "${artifact_file}" "${package_prefix}" "NexiLB package artifact")
    file(SIZE "${artifact_file}" actual_size)
    file(SHA256 "${artifact_file}" actual_sha256)
    if(NOT actual_size EQUAL expected_size OR
       NOT actual_sha256 STREQUAL expected_sha256)
      message(FATAL_ERROR
        "NexiLB package artifact does not match manifest: ${artifact_file}")
    endif()
    if(role STREQUAL "runtime")
      set(runtime_file "${artifact_file}")
      set(runtime_size "${expected_size}")
      set(runtime_sha256 "${expected_sha256}")
    elseif(role STREQUAL "case_verify")
      set(case_verify_file "${artifact_file}")
      set(case_verify_size "${expected_size}")
      set(case_verify_sha256 "${expected_sha256}")
    elseif(role STREQUAL "case_test")
      set(case_test_file "${artifact_file}")
      set(case_test_size "${expected_size}")
      set(case_test_sha256 "${expected_sha256}")
    elseif(role STREQUAL "public_header")
      set(header_file "${artifact_file}")
    elseif(role STREQUAL "public_cpp_header")
      set(cpp_header_file "${artifact_file}")
    elseif(role STREQUAL "abi_layout")
      set(layout_file "${artifact_file}")
    elseif(role STREQUAL "catalog_bundle")
      set(catalog_bundle_file "${artifact_file}")
    endif()
  endforeach()
  string(SHA256 actual_artifact_set_sha256 "${artifact_identity}")
  if(NOT actual_artifact_set_sha256 STREQUAL expected_artifact_set_sha256)
    message(FATAL_ERROR "NexiLB artifact-set hash does not match manifest")
  endif()

  foreach(required_role IN ITEMS runtime case_verify case_test public_header public_cpp_header abi_layout catalog_bundle)
    if(NOT required_role IN_LIST seen_roles)
      message(FATAL_ERROR "NexiLB manifest role is missing: ${required_role}")
    endif()
  endforeach()
  if(NOT header_file STREQUAL NexiLB_EXPECTED_PUBLIC_HEADER OR
     NOT cpp_header_file STREQUAL NexiLB_EXPECTED_PUBLIC_CPP_HEADER)
    message(FATAL_ERROR "NexiLB public header path does not match package config")
  endif()

  _nexilb_assert_imported_location(
    NexiLB::CaseVerify "${case_verify_file}" "NexiLB case verifier")
  _nexilb_assert_imported_location(
    NexiLB::CaseTest "${case_test_file}" "NexiLB case test driver")
  if(NOT layout_file STREQUAL NexiLB_ABI_LAYOUT_BASELINE)
    message(FATAL_ERROR "NexiLB ABI layout path does not match package config")
  endif()
  if(NOT catalog_bundle_file STREQUAL NexiLB_CATALOG_BUNDLE)
    message(FATAL_ERROR "NexiLB catalog bundle path does not match package config")
  endif()

  set(imported_runtime_locations)
  set(imported_runtime_sonames)
  get_target_property(imported_configurations
    NexiLB::Runtime IMPORTED_CONFIGURATIONS)
  foreach(imported_configuration IN LISTS imported_configurations)
    string(TOUPPER "${imported_configuration}" imported_configuration_upper)
    get_target_property(imported_location NexiLB::Runtime
      "IMPORTED_LOCATION_${imported_configuration_upper}")
    if(imported_location AND EXISTS "${imported_location}")
      file(REAL_PATH "${imported_location}" imported_location_real)
      list(APPEND imported_runtime_locations "${imported_location_real}")
    endif()
    get_target_property(imported_soname NexiLB::Runtime
      "IMPORTED_SONAME_${imported_configuration_upper}")
    if(imported_soname)
      get_filename_component(imported_soname_name "${imported_soname}" NAME)
      list(APPEND imported_runtime_sonames "${imported_soname_name}")
    endif()
  endforeach()
  get_target_property(imported_location NexiLB::Runtime IMPORTED_LOCATION)
  if(imported_location AND EXISTS "${imported_location}")
    file(REAL_PATH "${imported_location}" imported_location_real)
    list(APPEND imported_runtime_locations "${imported_location_real}")
  endif()
  get_target_property(imported_soname NexiLB::Runtime IMPORTED_SONAME)
  if(imported_soname)
    get_filename_component(imported_soname_name "${imported_soname}" NAME)
    list(APPEND imported_runtime_sonames "${imported_soname_name}")
  endif()
  list(REMOVE_DUPLICATES imported_runtime_locations)
  file(REAL_PATH "${runtime_file}" runtime_file_real)
  if(NOT runtime_file_real IN_LIST imported_runtime_locations)
    message(FATAL_ERROR
      "NexiLB runtime manifest path does not match the imported target")
  endif()
  get_filename_component(runtime_file_name "${runtime_file}" NAME)
  if(WIN32)
    if(NOT runtime_load_name STREQUAL runtime_file_name)
      message(FATAL_ERROR "Windows NexiLB runtime load name must equal the DLL name")
    endif()
  else()
    list(REMOVE_DUPLICATES imported_runtime_sonames)
    if(NOT runtime_load_name IN_LIST imported_runtime_sonames)
      message(FATAL_ERROR
        "NexiLB runtime load name does not match the imported target SONAME")
    endif()
  endif()

  set(NexiLB_RUNTIME_FILE "${runtime_file}" PARENT_SCOPE)
  set(NexiLB_RUNTIME_SIZE "${runtime_size}" PARENT_SCOPE)
  set(NexiLB_RUNTIME_SHA256 "${runtime_sha256}" PARENT_SCOPE)
  set(NexiLB_RUNTIME_LOAD_NAME "${runtime_load_name}" PARENT_SCOPE)
  set(NexiLB_CASE_VERIFY_FILE "${case_verify_file}" PARENT_SCOPE)
  set(NexiLB_CASE_VERIFY_SIZE "${case_verify_size}" PARENT_SCOPE)
  set(NexiLB_CASE_VERIFY_SHA256 "${case_verify_sha256}" PARENT_SCOPE)
  set(NexiLB_CASE_TEST_FILE "${case_test_file}" PARENT_SCOPE)
  set(NexiLB_CASE_TEST_SIZE "${case_test_size}" PARENT_SCOPE)
  set(NexiLB_CASE_TEST_SHA256 "${case_test_sha256}" PARENT_SCOPE)
  set(NexiLB_PUBLIC_HEADER "${header_file}" PARENT_SCOPE)
  set(NexiLB_PUBLIC_CPP_HEADER "${cpp_header_file}" PARENT_SCOPE)
  set(NexiLB_PACKAGE_STATE "${package_state}" PARENT_SCOPE)
endfunction()
